steps:
# This step runs the unit tests on the app
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test_app.py -v'

# This step builds the container image.
- name: 'gcr.io/$PROJECT_ID/cloud-build-demo'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/cloud-build-demo:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/$PROJECT_ID/cloud-build-demo'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/cloud-build-demo:$SHORT_SHA'