apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/k8s16-147307/flask-k8s:v1
        ports:
        - containerPort: 5000